name: palestine_trusted_device
description: Check if the device is trustworthy, rooted, jailbroken, developer mode is on, ...etc.
version: 0.0.8

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  # test: ^1.20.1

flutter:
  plugin:
    platforms:
      android:
        package: net.msayed.palestine_trusted_device
        pluginClass: PalestineTrustedDevicePlugin
      ios:
        pluginClass: PalestineTrustedDevicePlugin
